{% set name = "sym" %}
{% set version = "0.3.5" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sym-{{ version }}.tar.gz
  sha256: 854ddd18f0a1f94c9590012e50a139b499b407c90e9ebd407c40285627784ab8

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - sym
    - sym.tests
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/bjodah/sym
  summary: Unified wrapper for symbolic manipulation libraries in Python.
  doc_url: https://pythonhosted.org/sym/
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ProfLeao
    - bjodah
